const SIZES = ['SMALL', 'MEDIUM', 'LARGE'];
const STATES = ['IDLE', 'HOVER', 'ACTIVE', 'DISABLED', 'FOCUS'];
const LAYOUTS = ['WITHOUT_ICON', 'WITH_ICON'];

const SIZE_GROUP_GAP = 1000;
const MAIN_BUTTON_AND_INSTANCE_HORIZONTAL_OFFSET = 360;
const ICON_COMPONENT_TOP_OFFSET = 100;

export {
  SIZES,
  STATES,
  LAYOUTS,
  SIZE_GROUP_GAP,
  MAIN_BUTTON_AND_INSTANCE_HORIZONTAL_OFFSET,
  ICON_COMPONENT_TOP_OFFSET,
};
