const SIZES = ['SMALL', 'MEDIUM', 'LARGE'];
const STATES = ['IDLE', 'HOVER', 'ACTIVE', 'DISABLED', 'FOCUS'];
const LAYOUTS = ['WITHOUT_ICON', 'WITH_ICON'];

const GAP_BETWEEN_LAYOUTS = 600;
const GAP_BETWEEN_MAIN_BUTTON_AND_INSTANCE = 360;

export { SIZES, STATES, LAYOUTS, GAP_BETWEEN_LAYOUTS, GAP_BETWEEN_MAIN_BUTTON_AND_INSTANCE};